services:
  - type: web
    name: sistema-ecocardiograma
    env: python
    region: ohio
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ecocardiograma-db
          property: connectionString

databases:
  - name: ecocardiograma-db
    databaseName: ecocardiograma
    user: ecocardiograma_user
