services:
  - type: web
    name: sistema-ecocardiograma
    runtime: python3
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 main:app
    envVars:
      - key: SESSION_SECRET
        value: vidah-echo-system-secret-key-2025
      - key: FLASK_ENV
        value: production
    scaling:
      minInstances: 1
      maxInstances: 3

databases:
  - name: sistema-ecocardiograma-db
    databaseName: ecocardiograma
    user: postgres
    plan: free
