services:
  - type: web
    name: sistema-ecocardiograma
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --preload main:app
    plan: free
    healthCheckPath: /
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ecocardiograma-db
          property: connectionString
    autoDeploy: true

databases:
  - name: ecocardiograma-db
    databaseName: ecocardiograma
    user: admin
    plan: free
